#MANGA RECOMMENDATION PROGRAM
#THIS PROGRAM WOULD RECOMMEND OF THE BEST MANGA RECOMMENDATION BASED ON THE GENRE YOU LIKE THE MOST
genre=input("ENTER YOUR FAVOUIRATE MANGA GENRE [SHONEN/SHENIN/ROMANTIC/SPORTS]:").lower()
length=(input("ENTER THE LENGTH OF THE MANGA YOU WOULD PREFFER[SHORT,MEDIUM,LONG]:")).lower()
story=input("ENTER THE TYPE OF CONCEPT/ STORY YOU WOULD PREFFER[HAPPY,SAD,MINDBENDING]:").lower()
if(genre=="shonen"):
    if(length=="short"):
        if(story=="happy"):
            print("SPY X FAMILY IS A GOOD CHOICE FOR YOU")

